Controllers/EVENTsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdventureLandWebapp.Data;
using AdventureLandWebapp.Models;
using Microsoft.AspNetCore.Authorization;

namespace AdventureLandWebapp.Controllers
{
    public class EVENTsController : Controller
    {
        private readonly AdventureLandWebappContext _context;

        public EVENTsController(AdventureLandWebappContext context)
        {
            _context = context;
        }

        // GET: EVENTs
        public async Task<IActionResult> Index()
        {
              return _context.EVENT != null ? 
                          View(await _context.EVENT.ToListAsync()) :
                          Problem("Entity set 'AdventureLandWebappContext.EVENT'  is null.");
        }

        // GET: EVENTs/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.EVENT == null)
            {
                return NotFound();
            }

            var eVENT = await _context.EVENT
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (eVENT == null)
            {
                return NotFound();
            }

            return View(eVENT);
        }

        // GET: EVENTs/Create
        [Authorize(Roles = ("Manager, Admin"))]
        public IActionResult Create()
        {
            return View();
        }

        // POST: EVENTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = ("Manager, Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueID,EventID,EventName,Event_Started,Event_Ended")] EVENT eVENT)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eVENT);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eVENT);
        }

        // GET: EVENTs/Edit/5
        [Authorize(Roles = ("Manager, Admin"))]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.EVENT == null)
            {
                return NotFound();
            }

            var eVENT = await _context.EVENT.FindAsync(id);
            if (eVENT == null)
            {
                return NotFound();
            }
            return View(eVENT);
        }

        // POST: EVENTs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = ("Manager, Admin"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueID,EventID,EventName,Event_Started,Event_Ended")] EVENT eVENT)
        {
            if (id != eVENT.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eVENT);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EVENTExists(eVENT.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eVENT);
        }

        // GET: EVENTs/Delete/5
        [Authorize(Roles = ("Manager, Admin"))]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.EVENT == null)
            {
                return NotFound();
            }

            var eVENT = await _context.EVENT
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (eVENT == null)
            {
                return NotFound();
            }

            return View(eVENT);
        }

        // POST: EVENTs/Delete/5
        [Authorize(Roles = ("Manager, Admin"))]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.EVENT == null)
            {
                return Problem("Entity set 'AdventureLandWebappContext.EVENT'  is null.");
            }
            var eVENT = await _context.EVENT.FindAsync(id);
            if (eVENT != null)
            {
                _context.EVENT.Remove(eVENT);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EVENTExists(int id)
        {
          return (_context.EVENT?.Any(e => e.EventID == id)).GetValueOrDefault();
        }
    }
}

Controllers/SHOPsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdventureLandWebapp.Data;
using AdventureLandWebapp.Models;
using Microsoft.AspNetCore.Authorization;

namespace AdventureLandWebapp.Controllers
{
    public class SHOPsController : Controller
    {
        private readonly AdventureLandWebappContext _context;

        public SHOPsController(AdventureLandWebappContext context)
        {
            _context = context;
        }

        // GET: SHOPs
        public async Task<IActionResult> Index()
        {
              return _context.SHOP != null ? 
                          View(await _context.SHOP.ToListAsync()) :
                          Problem("Entity set 'AdventureLandWebappContext.SHOP'  is null.");
        }

        // GET: SHOPs/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.SHOP == null)
            {
                return NotFound();
            }

            var sHOP = await _context.SHOP
                .FirstOrDefaultAsync(m => m.ShopID == id);
            if (sHOP == null)
            {
                return NotFound();
            }

            return View(sHOP);
        }

        // GET: SHOPs/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: SHOPs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShopID,ShopName,Location,Phone_Number")] SHOP sHOP)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sHOP);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sHOP);
        }

        // GET: SHOPs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.SHOP == null)
            {
                return NotFound();
            }

            var sHOP = await _context.SHOP.FindAsync(id);
            if (sHOP == null)
            {
                return NotFound();
            }
            return View(sHOP);
        }

        // POST: SHOPs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShopID,ShopName,Location,Phone_Number")] SHOP sHOP)
        {
            if (id != sHOP.ShopID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sHOP);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SHOPExists(sHOP.ShopID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sHOP);
        }

        // GET: SHOPs/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.SHOP == null)
            {
                return NotFound();
            }

            var sHOP = await _context.SHOP
                .FirstOrDefaultAsync(m => m.ShopID == id);
            if (sHOP == null)
            {
                return NotFound();
            }

            return View(sHOP);
        }

        // POST: SHOPs/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.SHOP == null)
            {
                return Problem("Entity set 'AdventureLandWebappContext.SHOP'  is null.");
            }
            var sHOP = await _context.SHOP.FindAsync(id);
            if (sHOP != null)
            {
                _context.SHOP.Remove(sHOP);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SHOPExists(int id)
        {
          return (_context.SHOP?.Any(e => e.ShopID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html lang="en">
<head>
    <style>
        nav{
            font-family: Garamond;
            color: whitesmoke;
            font-size: 24pt;
            text-shadow: 2px 2px black;
            background: rgba(20, 21, 23, 0.7);
        }

        a {
            font-family: Garamond;
            color: whitesmoke;
            font-size: 24pt;
            text-shadow: none;
        }

        a:visited {
            font-family: Garamond;
            color: whitesmoke;
            font-size: 24pt;
            text-shadow: 2px 2px black;
        }

        .dropdown {
            display: inline-block;
            position: relative;
        }

        button {
            color: whitesmoke;
            border: none;
            border-radius: 5px;
            padding: 5px 10px;
            font-size: 18px;
            background: none;
            cursor: pointer;
        }

        button:hover {
                background: rgba(20, 21, 23, 0.9);
        }

        .dropdown-options {
            display: none;
            position: absolute;
            overflow: auto;
            background: rgba(20, 21, 23, 0.9);
            border-radius: 5px;
            box-shadow: 0px 10px 10px 0px rgba(0,0,0,0.4);
        }

        .dropdown:hover .dropdown-options {
            display: block;
        }

        .dropdown-options a {
            display: block;
            color: whitesmoke;
            padding: 5px;
            text-decoration: none;
            padding: 20px 40px;
        }

        .dropdown-options a:visited {
            display: block;
            color: whitesmoke;
            padding: 5px;
            text-decoration: none;
            padding: 20px 40px;
        }

        .dropdown-options a:hover {
            background: rgba(20, 21, 23, 0.7);
            border-radius: 5px;
        }
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adventure Land</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdventureLandWebapp.styles.css" asp-append-version="true" />
</head>
<body>
    <style>
        body {
            background-color: dimgrey;
        }        
        table {
            background-color: azure;
            color: black;
            text-align: center;
        }
        a:visited {
            font-family: Garamond;
            color: rebeccapurple;
            font-size: 24pt;
            text-shadow: 2px 2px black;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Map">Map</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="EVENTs" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="SHOPs" asp-action="Index">Shops</a>
                        </li>
                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="ATTRACTIONs" asp-action="Index">Attractions</a>
                        </li>

                        <li class="nav-item text-light">
                            <a class="nav-link" asp-area="" asp-controller="AppRoles" asp-action="Index">ROLES(T)</a>
                        </li>
                    </ul>

                    @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Attendant"))
                    {
                        <div class="dropdown">
                            <button>Guest/Tickets</button>
                            <div class="dropdown-options">
                                <a class="nav-link" asp-area="" asp-controller="GUESTs" asp-action="Index">Guests</a>
                                <a class="nav-link" asp-area="" asp-controller="GUEST_REC" asp-action="Index">Guest Ledger</a>
                                <a class="nav-link" asp-area="" asp-controller="TICKETs" asp-action="Index">Tickets</a>

                            </div>
                        </div>
                    }

                     @if (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Maintenance"))
                    {
                        <div class="dropdown">
                            <button>Maintanence</button>
                            <div class="dropdown-options">
                                <a class="nav-link" asp-area="" asp-controller="MAINTENENCE_PERSONNEL_REC" asp-action="Index">Maint. Work</a>
                                <a class="nav-link" asp-area="" asp-controller="MAINTENENCE_REC" asp-action="Index">Maint. Records</a>
                                <a class="nav-link" asp-area="" asp-controller="ATTRACTIONs" asp-action="Index">Attractions</a>
                            </div>
                        </div>
                    }

                    @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {
                        <div class="dropdown">
                            <button>Management</button>
                            <div class="dropdown-options">
                                <a class="nav-link" asp-area="" asp-controller="EMPLOYEEs" asp-action="Index">Employees</a>
                                <a class="nav-link" asp-area="" asp-controller="PERSONNEL_WORK_REC" asp-action="Index">Work Records</a>
                                <a class="nav-link" asp-area="" asp-controller="SHOP_EMPLOYEE" asp-action="Index">Shop Personnel</a>
                                <a class="nav-link" asp-area="" asp-controller="SHOP_INVENTORY_ITEM" asp-action="Index">Shop Inventories</a>
                                <a class="nav-link" asp-area="" asp-controller="SHOP_ITEM" asp-action="Index">Shop Items</a>

                            </div>
                        </div>
                            
                      
                    }

                    @if (User.IsInRole("Admin"))
                    {
                        <div class="dropdown">
                            <button>Admin</button>
                            <div class="dropdown-options">
                                <a class="nav-link" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                                <a class="nav-link" asp-area="" asp-controller="TICKET_TYPES" asp-action="Index">Ticket Types</a>
                                <a class="nav-link" asp-area="" asp-controller="REPORTs" asp-action="Index">Reports</a>
                            </div>
                        </div>
                    }

                </div>
            </div>
            <partial name ="_LoginPartial"/> 
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AdventureLandWebapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>